
services:
  app1:
    build: ./app_web
    container_name: app1
    environment:
      - INSTANCE_NAME=app1
    networks:
      - app_net
    depends_on:
      - db

  app2:
    build: ./app_web
    container_name: app2
    environment:
      - INSTANCE_NAME=app2
    networks:
      - app_net
    depends_on:
      - db

  app3:
    build: ./app_web
    container_name: app3
    environment:
      - INSTANCE_NAME=app3
    networks:
      - app_net
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
